def ind_state(state):
    state_cap = {
        "Andhra pradesh" : "Hyderabad (Proposed Capital Amaravati)",
        "Arunachal pradesh" : "Itanagar",
        "Assam"	: "Dispur",
        "Bihar" : "Patna",
        "Chhattisgarh" : "Raipur",
        "Goa" : "Panaji",
        "Gujarat" : "Gandhinagar",
        "Haryana" : "Chandigarh",
        "Himachal" : "Pradesh",
        "Jharkhand" : "Ranchi",
        "Karnataka" : "Bengaluru" ,
        "Kerala" : "Thiruvananthapuram",
        "Madhya pradesh" : "Bhopal",
        "Maharashtra" : "Mumbai",
        "Manipur" : "Imphal",
        "Meghalaya" : "Shillong",
        "Mizoram" : "Aizawl",
        "Nagaland" : "Kohima",
        "Odisha" : "Bhubaneswar",
        "Punjab" : "Chandigarh",
        "Rajasthan" : "Jaipur",
        "Sikkim" : "Gangtok",
        "Tamil nadu" : "Chennai",
        "Telangana" : "Hyderabad",
        "Tripura" : "Agartala",
        "Uttar pradesh" : "Lucknow",
        "Uttarakhand" : "Dehradun",
        "West bengal" : "Kolkata"
    }

    if state not in state_cap.keys():
        return -1
    return state_cap[state]


def world_caps(country):
    import json
    country_cap = {
        "afghanistan" : "Kabul",
        "albania" : "Tirana",
        "algeria" : "Alger",
        "american samoa" : "Fagatogo",
        "andorra" : "Andorra la Vella",        
        "angola" : "Luanda",
        "anguilla" : "The Valley",
        "antigua and barbuda" : "Saint John's",
        "argentina" : "Buenos Aires",
        "armenia" : "Yerevan",
        "aruba" : "Oranjestad",
        "australia" : "Canberra",
        "austria" : "Wien",
        "azerbaijan" : "Baku",
        "bahamas" : "Nassau",
        "bahrain" : "al-Manama",
        "bangladesh" : "Dhaka",
        "barbados" : "Bridgetown",
        "belarus" : "Minsk",
        "belgium" : "Bruxelles [Brussel]",
        "belize" : "Belmopan",
        "benin" : "Porto-Novo",
        "bermuda" : "Hamilton",
        "bhutan" : "Thimphu",
        "bolivia" : "La Paz",
        "bosnia and herzegovina" : "Sarajevo",
        "botswana" : "Gaborone",
        "brazil" : "BrasÃ­lia",
        "brunei" : "Bandar Seri Begawan",
        "bulgaria" : "Sofia",
        "burkina faso" : "Ouagadougou",
        "burundi" : "Bujumbura",
        "cambodia" : "Phnom Penh",
        "cameroon" : "Yaound",
        "canada" : "Ottawa",
        "cape verde" : "Praia",
        "cayman islands" : "George Town",
        "central african republic" : "Bangui",
        "chad" : "N'Djam",
        "chile" : "Santiago de Chile",
        "china" : "Peking",
        "christmas island" : "Flying Fish Cove",
        "cocos (keeling) islands" : "West Island",
        "colombia" : "Santaf",
        "comoros" : "Moroni",
        "congo" : "Brazzaville",
        "cook islands" : "Avarua",
        "costa rica" : "San Jos",
        "croatia" : "Zagreb",
        "cuba" : "La Habana",
        "cyprus" : "Nicosia",
        "czech republic" : "Praha",
        "denmark" : "Copenhagen",
        "djibouti" : "Djibouti",
        "dominica" : "Roseau",
        "dominican republic" : "Santo Domingo de Guzm",
        "east timor" : "Dili",
        "ecuador" : "Quito",
        "egypt" : "Cairo",
        "el salvador" : "San Salvador",
        "england" : "London",
        "equatorial guinea" : "Malabo",
        "eritrea" : "Asmara",
        "estonia" : "Tallinn",
        "ethiopia" : "Addis Abeba",
        "falkland islands" : "Stanley",
        "faroe islands" : "TÃ³rshavn",
        "fiji islands" : "Suva",
        "finland" : "Helsinki [Helsingfors]",
        "france" : "Paris",
        "french guiana" : "Cayenne",
        "french polynesia" : "Papeete",
        "gabon" : "Libreville",
        "gambia" : "Banjul",
        "georgia" : "Tbilisi",
        "germany" : "Berlin",
        "ghana" : "Accra",
        "gibraltar" : "Gibraltar",
        "greece" : "Athenai",
        "greenland" : "Nuuk",
        "grenada" : "Saint George's",
        "guadeloupe" : "Basse-Terre",
        "guam" : "Aga",
        "guatemala" : "Ciudad de Guatemala",
        "guinea" : "Conakry",
        "guinea-bissau" : "Bissau",
        "guyana" : "Georgetown",
        "haiti" : "Port-au-Prince",
        "holy see (vatican city state)" : "Citt",
        "honduras" : "Tegucigalpa",
        "hong kong" : "Victoria",
        "hungary" : "Budapest",
        "iceland" : "Reykjav",
        "india" : "New Delhi",
        "indonesia" : "Jakarta",
        "iran" : "Tehran",
        "iraq" : "Baghdad",
        "ireland" : "Dublin",
        "israel" : "Jerusalem",
        "italy" : "Roma",
        "ivory coast" : "Yamoussoukro",
        "jamaica" : "Kingston",
        "japan" : "Tokyo",
        "jordan" : "Amman",
        "kazakhstan" : "Astana",
        "kenya" : "Nairobi",
        "kiribati" : "Bairiki",
        "kuwait" : "Kuwait",
        "kyrgyzstan" : "Bishkek",
        "laos" : "Vientiane",
        "latvia" : "Riga",
        "lebanon" : "Beirut",
        "lesotho" : "Maseru",
        "liberia" : "Monrovia",
        "libyan arab jamahiriya" : "Tripoli",
        "liechtenstein" : "Vaduz",
        "lithuania" : "Vilnius",
        "luxembourg" : "Luxembourg [Luxemburg/L",
        "macao" : "Macao",
        "north macedonia" : "Skopje",
        "madagascar" : "Antananarivo",
        "malawi" : "Lilongwe",
        "malaysia" : "Kuala Lumpur",
        "maldives" : "Male",
        "mali" : "Bamako",
        "malta" : "Valletta",
        "marshall islands" : "Dalap-Uliga-Darrit",
        "martinique" : "Fort-de-France",
        "mauritania" : "Nouakchott",
        "mauritius" : "Port-Louis",
        "mayotte" : "Mamoutzou",
        "mexico" : "Ciudad de M",
        "micronesia, federated states of" : "Palikir",
        "moldova" : "Chisinau",
        "monaco" : "Monaco-Ville",
        "mongolia" : "Ulan Bator",
        "montenegro" : "Podgorica",
        "montserrat" : "Plymouth",
        "morocco" : "Rabat",
        "mozambique" : "Maputo",
        "myanmar" : "Rangoon (Yangon)",
        "namibia" : "Windhoek",
        "nauru" : "Yaren",
        "nepal" : "Kathmandu",
        "netherlands" : "Amsterdam",
        "netherlands antilles" : "Willemstad",
        "new caledonia" : "Noum",
        "new zealand" : "Wellington",
        "nicaragua" : "Managua",
        "niger" : "Niamey",
        "nigeria" : "Abuja",
        "niue" : "Alofi",
        "norfolk island" : "Kingston",
        "north korea" : "Pyongyang",
        "northern ireland" : "Belfast",
        "northern mariana islands" : "Garapan",
        "norway" : "Oslo",
        "oman" : "Masqat",
        "pakistan" : "Islamabad",
        "palau" : "Koror",
        "palestine" : "Gaza",
        "panama" : "Ciudad de Panam",
        "papua new guinea" : "Port Moresby",
        "paraguay" : "Asunci",
        "peru" : "Lima",
        "philippines" : "Manila",
        "pitcairn" : "Adamstown",
        "poland" : "Warszawa",
        "portugal" : "Lisboa",
        "puerto rico" : "San Juan",
        "qatar" : "Doha",
        "reunion" : "Saint-Denis",
        "romania" : "Bucuresti",
        "russian federation" : "Moscow",
        "rwanda" : "Kigali",
        "saint helena" : "Jamestown",
        "saint kitts and nevis" : "Basseterre",
        "saint lucia" : "Castries",
        "saint pierre and miquelon" : "Saint-Pierre",
        "saint vincent and the grenadines" : "Kingstown",
        "samoa" : "Apia",
        "san marino" : "San Marino",
        "sao tome and principe" : "S",
        "saudi arabia" : "Riyadh",
        "scotland" : "Edinburgh",
        "senegal" : "Dakar",
        "serbia" : "Belgrade",
        "seychelles" : "Victoria",
        "sierra leone" : "Freetown",
        "singapore" : "Singapore",
        "slovakia" : "Bratislava",
        "slovenia" : "Ljubljana",
        "solomon islands" : "Honiara",
        "somalia" : "Mogadishu",
        "south africa" : "Pretoria",
        "south korea" : "Seoul",
        "south sudan" : "Juba",
        "spain" : "Madrid",
        "sudan" : "Khartum",
        "suriname" : "Paramaribo",
        "svalbard and jan mayen" : "Longyearbyen",
        "swaziland" : "Mbabane",
        "sweden" : "Stockholm",
        "switzerland" : "Bern",
        "syria" : "Damascus",
        "tajikistan" : "Dushanbe",
        "tanzania" : "Dodoma",
        "thailand" : "Bangkok",
        "the democratic republic of congo" : "Kinshasa",
        "togo" : "LomÃ©",
        "tokelau" : "Fakaofo",
        "tonga" : "Nuku'alofa",
        "trinidad and tobago" : "Port-of-Spain",
        "tunisia" : "Tunis",
        "turkey" : "Ankara",
        "turkmenistan" : "Ashgabat",
        "turks and caicos islands" : "Cockburn Town",
        "tuvalu" : "Funafuti",
        "uganda" : "Kampala",
        "ukraine" : "Kyiv",
        "united arab emirates" : "Abu Dhabi",
        "united kingdom" : "London",
        "united states" : "Washington",
        "uruguay" : "Montevideo",
        "uzbekistan" : "Toskent",
        "vanuatu" : "Port-Vila",
        "venezuela" : "Caracas",
        "vietnam" : "Hanoi",
        "virgin islands, british" : "Road Town",
        "virgin islands, u.s." : "Charlotte Amalie",
        "wales" : "Cardiff",
        "wallis and futuna" : "Mata-Utu",
        "western sahara" : "El-Aai",
        "yemen" : "Sanaa",
        "zambia" : "Lusaka",
        "zimbabwe" : "Harare"
    }

    # code to generate dictionary from json:
    # with open('worldCap.json') as json_file:
    #     data = json.load(json_file)
    #     for i in data:
    #         if type(i['city']) == str:
    #             print('"' + i['country'].lower() + '"' + " : " + '"' + i['city'] + '",')

    if country not in country_cap.keys():
        return -1
    return country_cap[country]